"""empty message

Revision ID: 0c40b21429bd
Revises: 016b3520e3a5
Create Date: 2022-02-09 15:16:31.838435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c40b21429bd'
down_revision = '016b3520e3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('upload_time', sa.DateTime(), nullable=True))
    op.drop_column('video', 'upload_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('video', 'upload_time')
    # ### end Alembic commands ###
