version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "80:5000"
    command: python main.py
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/usr/src/
    depends_on:
      - db
    env_file:
      - ./app/.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env

  db-test:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db

volumes:
  postgres_data:
