version: '3.7'

services:
  web:
    build: .
    ports:
      - "80:5000"
    command: python main.py
    volumes:
      - .:/usr/src/

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env

volumes:
  postgres_data:
