name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create File .env
        run: |
          echo some data > .env
      - name: Create File
        run: |
          echo some data > .env.db
      - name: Show file content
        run: |
          pwd
          ls -la
          cat .env.db
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec -T web pytest
      - name: PreCommit install
        run: docker-compose exec -T web poetry add pylint mypy types-requests
      - run: docker-compose exec -T web pylint --disable=all --enable=unused-import $(git ls-files '*.py')
      - run: docker-compose exec -T web mypy --strict $(git ls-files '*.py')
