# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          DATABASE: "postgresql"
          SQL_HOST: "db"
          SQL_USER: "flask_user"
          SQL_PASSWORD: "1234567816"
          SQL_DB_NAME: "video_streaming"
          SQL_PORT: "5432"
          SECRET_KEY: "146EtHWvxaInR3YB3d2Cdtn4emQcUBWw"
          FLASK_APP: "main"
          FLASK_ENV: "development"
          directory: app/
          file_name: .env

      - name: create .env.db file
        uses: SpicyPizza/create-envfile@v1
        with:
          POSTGRES_USER: "flask_user"
          POSTGRES_PASSWORD: "1234567816"
          POSTGRES_DB: "video_streaming"
          directory: app/
          file_name: .env.db
      # Runs a single command using the runners shell
      - name: run docker
        shell: "docker-compose up -d --build"

      # Runs a set of commands using the runners shell
      - name: run tests
        run: pytest app/tests
