name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create File app/.env
        run: |
          echo SECRET_KEY='some_secret' > app/.env

          echo DATABASE='postgresql' >> app/.env
          echo SQL_HOST='db' >> app/.env
          echo POSTGRES_USER='test_user' >> app/.env
          echo POSTGRES_PASSWORD='test_password' >> app/.env
          echo POSTGRES_DB='test_db' >> app/.env
          echo SQL_PORT='5432' >> app/.env
      - name: Build docker
        run: docker-compose up -d
      - name: Test
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec -T web pytest
#      - name: PreCommit install
#        run: docker-compose exec -T web poetry add pylint mypy types-requests
#      - run: docker-compose exec -T web pylint --disable=all --enable=unused-import $(git ls-files '*.py')
#      - run: docker-compose exec -T web mypy --strict $(git ls-files '*.py')
