name: PreCommit

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: docker-compose up -d
      - name: PreCommit install
        run: docker-compose exec -T web poetry add mypy types-requests flake8
      - run: docker-compose exec -T web flake8 .
      - run: docker-compose exec -T web mypy .
