name: Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create File app/.env
        run: |
          echo SECRET_KEY='some_secret' > app/.env

          echo DATABASE='postgresql' >> app/.env
          echo POSTGRES_HOST='db' >> app/.env
          echo POSTGRES_USER='test_user_1' >> app/.env
          echo POSTGRES_PASSWORD='test_password_1' >> app/.env
          echo POSTGRES_DB='test_db_1' >> app/.env
          echo POSTGRES_PORT='5432' >> app/.env
      - name: Build docker
        run: docker-compose up
      - name: Test
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec -T web pytest
